name: Lint code using ruff

on:
  push:
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest
    if: github.repository != 'cogent3/SciNexus'
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Format code using ruff
        run: uv run --group dev nox -s fmt

      - name: Commit changes
        uses: EndBug/add-and-commit@645ecc0dd0a57f4d86d26c0aa5fc42c0a856fbca # v11.0.0
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "STY: pre-commit linting with ruff"
          add: "."
